apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-api-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: book-api
            port:
              number: 80